In [2]:
from glob import glob
from random import randint
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sys
import os

In [4]:
start, end = 0, 50000
lst = [randint(start, end) for i in range(0, 20000)]

In [5]:
lst[:5]

[15594, 10212, 5546, 23397, 43886]

<img src="Ocomplexity.png" />

![arrayAlgorithm](arrayAlgorithm.png)

### Insertion Sort

### Quicksort


https://www.geeksforgeeks.org/quick-sort/

Quicksort numpy implementation

In [6]:
%%time
np.sort(lst, kind='quicksort')

CPU times: user 3.89 ms, sys: 1.91 ms, total: 5.8 ms
Wall time: 4.83 ms


array([    2,     3,    12, ..., 49996, 49998, 49998])

Python quicksort implementation

### Mergesort

Numpy mergesort implementation

In [7]:
%%time
np.sort(lst, kind='mergesort')

CPU times: user 3.74 ms, sys: 1.69 ms, total: 5.42 ms
Wall time: 4.9 ms


array([    2,     3,    12, ..., 49996, 49998, 49998])

Python mergesort implementation

### Heapsort

https://www.geeksforgeeks.org/heap-sort/

Numpy heapsort implementation

In [10]:
%%time
np.sort(lst, kind='heapsort')

CPU times: user 4.88 ms, sys: 1.93 ms, total: 6.81 ms
Wall time: 5.09 ms


array([    2,     3,    12, ..., 49996, 49998, 49998])

Python heapsort implementation

### Radix

https://www.geeksforgeeks.org/radix-sort/

### Timsort

https://www.geeksforgeeks.org/timsort/

Numpy mix between radix and timsort

In [13]:
%%time
np.sort(lst, kind='stable')

CPU times: user 4.67 ms, sys: 1.43 ms, total: 6.11 ms
Wall time: 4.66 ms


array([    2,     3,    12, ..., 49996, 49998, 49998])